development:
  bucket: 3rdnote
  access_key_id: 
  secret_access_key: 
  max_file_size: 10485760
  acl: public-read
    
test:
  bucket: 3rdnote
  access_key_id: 
  secret_access_key: 
  max_file_size: 10485760
  acl: public-read
    
production:
  bucket: 3rdnote
  access_key_id: 
  secret_access_key: 
  max_file_size: 10485760
  acl: public-read
  